=== Nelfia/NFP121/Projet/out/production/Projet/generateur.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT donnees (lot*)>
<!ELEMENT lot (donnee*)>
<!ATTLIST lot
        name CDATA #REQUIRED
        type CDATA #IMPLIED
        format CDATA #IMPLIED>
<!ELEMENT donnee (position)>
<!ELEMENT position (valeur)>
<!ATTLIST position
        x CDATA #REQUIRED
        y CDATA #REQUIRED>
<!ELEMENT valeur (#PCDATA)>

=== Nelfia/NFP121/Projet/src/fichiersGeneres/valides--genere.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE donnees SYSTEM "generateur.dtd">
<donnees>
  <lot name="manuelles">
    <donnee>
      <position x="1" y="1">
        <valeur>5.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>2.0</valeur>
      </position>
    </donnee>
  </lot>
  <lot name="donnees.txt">
    <donnee>
      <position x="1" y="1">
        <valeur>4.2</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>5.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>6.3</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>1.6</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>0.8</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>1.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>5.0</valeur>
      </position>
    </donnee>
  </lot>
  <lot name="donnees2-f2.txt">
    <donnee>
      <position x="3" y="1">
        <valeur>0.5</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="3">
        <valeur>1.5</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>4.2</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>5.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>6.3</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>1.6</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>0.8</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>1.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="7" y="2">
        <valeur>5.0</valeur>
      </position>
    </donnee>
  </lot>
  <lot name="donnees2.xml">
    <donnee>
      <position x="2" y="2">
        <valeur>5.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>2.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="4" y="2">
        <valeur>3.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="2" y="2">
        <valeur>0.5</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="3" y="2">
        <valeur>6.5</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="2" y="2">
        <valeur>1.0</valeur>
      </position>
    </donnee>
  </lot>
  <lot name="donnees-erreurs.txt">
    <donnee>
      <position x="7" y="2">
        <valeur>3.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="3" y="1">
        <valeur>0.5</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="3">
        <valeur>1.5</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>4.2</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>5.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>6.3</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>1.6</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>0.8</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>1.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="7" y="2">
        <valeur>5.0</valeur>
      </position>
    </donnee>
  </lot>
  <lot name="donneesGenereesParSwing.txt">
    <donnee>
      <position x="2" y="4">
        <valeur>6.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>2.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>2.5</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>4.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="2" y="1">
        <valeur>6.5</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="2" y="2">
        <valeur>0.2</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="6" y="2">
        <valeur>0.8</valeur>
      </position>
    </donnee>
  </lot>
</donnees>

=== Nelfia/NFP121/Projet/out/production/Projet/fichiersGeneres/normalisees--genere.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE donnees SYSTEM "generateur.dtd">
<donnees>
  <lot name="donnees.txt">
    <donnee>
      <position x="1" y="1">
        <valeur>58.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>83.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>23.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>28.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="2" y="1">
        <valeur>100.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>56.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>35.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>9.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>4.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>6.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>28.0</valeur>
      </position>
    </donnee>
  </lot>
  <lot name="donnees2-f2.txt">
    <donnee>
      <position x="1" y="1">
        <valeur>58.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>83.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>23.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>28.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="2" y="1">
        <valeur>100.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>56.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>35.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>9.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>4.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>6.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>28.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="3" y="1">
        <valeur>3.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="3">
        <valeur>8.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>23.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>28.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="2" y="1">
        <valeur>100.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>56.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>35.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>9.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>4.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>6.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="7" y="2">
        <valeur>28.0</valeur>
      </position>
    </donnee>
  </lot>
  <lot name="donnees-erreurs">
    <donnee>
      <position x="1" y="1">
        <valeur>58.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>83.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>23.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>28.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="2" y="1">
        <valeur>100.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>56.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>35.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>9.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>4.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>6.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>28.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="3" y="1">
        <valeur>3.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="3">
        <valeur>8.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>23.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>28.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="2" y="1">
        <valeur>100.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>56.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>35.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>9.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>4.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>6.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="7" y="2">
        <valeur>28.0</valeur>
      </position>
    </donnee>
  </lot>
</donnees>

=== Nelfia/NFP121/Projet/src/fichiersGeneres/brut--genere.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE donnees SYSTEM "generateur.dtd">
<donnees>
  <lot name="manuelles">
    <donnee>
      <position x="1" y="1">
        <valeur>5.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="2">
        <valeur>2.0</valeur>
      </position>
    </donnee>
    <donnee>
      <position x="1" y="1">
        <valeur>-1.0</valeur>
      </position>
    </donnee>
  </lot>
</donnees>
